repos:
    # general hooks to verify or beautify code
    - repo: http://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        exclude: ".helm"
      - id: detect-aws-credentials
        args: [
          --allow-missing-credentials,
          --credentials-file, docker-compose/.env,
        ]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix]

    # sort imports
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          files: ^(breastcancer|tests)
          args: ["--profile", "black", "--trailing-comma", "--multi-line", "3"]

    # autodelete unused imports
    - repo: https://github.com/hadialqattan/pycln
      rev: v1.1.0
      hooks:
        - id: pycln
          args: [ --all ]